# shard manager service configuration
shardManager:
  image: golemservices/golem-shard-manager:${GOLEM_IMAGES_VERSION:-latest}
  imagePullPolicy: Always
  ports:
    http: 8081
    grpc: 9001
  service:
    type: ClusterIP
  redis:
    port: 6379
    host: redis
    username: ""
    database: 0
    password:
      type: none # secret or plain, or none if no auth
      plain: ""
      secret: # password from kubernetes secret
        name: golem-redis
        key: redis-password
#  nodeSelector:  # added, if defined, see: https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/

# worker executor service configuration
workerExecutor:
  image: golemservices/golem-worker-executor:${GOLEM_IMAGES_VERSION:-latest}
  imagePullPolicy: Always
  replica: 1
  ports:
    http: 8080
    grpc: 9000
  service:
    type: ClusterIP
  redis:
    port: 6379
    host: golem-redis-master
    username: ""
    database: 0
    password:
      type: secret # secret or plain, or none if no auth
      plain: ""
      secret: # password from kubernetes secret
        name: golem-redis
        key: redis-password
#  nodeSelector: # added, if defined, see: https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/

# worker service configuration
workerService:
  image: golemservices/golem-worker-service:${GOLEM_IMAGES_VERSION:-latest}
  imagePullPolicy: Always
  replica: 1
  ports:
    http: 9005
    requestHttp: 9006 # worker API Gateway
    grpc: 9007
  service:
    type: ClusterIP
  redis:
    port: 6379
    host: redis
    username: ""
    database: 0
    password:
      type: none
      plain: ""
      secret:
        name: golem-redis
        key: redis-password
  registryService:
    host: golem-registry-service
    port: 9001
  shardManager:
    host: golem-shard-manager
    port: 9001
#  nodeSelector: # added, if defined, see: https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/

# component compilation service configuration
componentCompilationService:
  image: golemservices/golem-component-compilation-service:${GOLEM_IMAGES_VERSION:-latest}
  imagePullPolicy: Always
  replica: 1
  ports:
    http: 8084
    grpc: 9091
  service:
    type: ClusterIP
#  nodeSelector: # added, if defined, see: https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/

# registry service configuration
registryService:
  image: golemservices/registry-service:${GOLEM_IMAGES_VERSION:-latest}
  imagePullPolicy: Always
  replica: 1
  ports:
    http: 9000
    grpc: 9001
  service:
    type: ClusterIP
  postgres:
    port: 5432
    host: postgres
    database: golem_db
    username: golem_user
    password:
      type: plain
      plain: "golem_password"

# debugging service configuration
debuggingService:
  image: golemservices/golem-debugging-service:${GOLEM_IMAGES_VERSION:-latest}
  imagePullPolicy: Always
  replica: 1
  ports:
    http: 9002
  service:
    type: ClusterIP
  redis:
    port: 6379
    host: redis
    username: ""
    database: 0
    password:
      type: none
      plain: ""
      secret:
        name: golem-redis
        key: redis-password

# logging configuration - used in all services
logging:
  json: false # true, if json log output should be used

# service account name  - used in all services, see: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccountName: golem-sa-default

# environment variables for all services
envVars:
  GOLEM_IMAGES_VERSION: "latest"
  ADMIN_TOKEN: ""
  MARKETING_TOKEN: ""

env: default

# component store configuration
componentStore:
  type: pvc # pvc or s3
  pvc:
    storageClassName: hostpath
    storageSize: 5Gi
    accessMode: ReadWriteOnce
  s3:
    objectPrefix: ""
    bucket: ""
    region: "us-east-1"
    useMinioCredentials: false
    awsEndpointUrl: ""

# worker executor store configuration
workerExecutorStore:
  type: pvc # pvc or s3
  pvc:
    storageClassName: hostpath
    storageSize: 5Gi
    accessMode: ReadWriteOnce
  s3:
    objectPrefix: ""
    region: "us-east-1"
    compilationCacheBucket: "compilation-cache"
    customDataBucket: "custom-data"
    oplogPayloadBucket: "oplog-payload"
    compressedOplogBuckets: "[oplog-archive-1]"
    useMinioCredentials: false
    awsEndpointUrl: ""

# API ingress
ingress:
  type: nginx # ngnix or aws alb
  nginx:
    annotations: # see: https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
  alb:
    annotations: # see: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.8/guide/ingress/annotations/
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip

# worker API Gateway ingress
ingressWorkerRequest:
  type: none # none or aws alb
  alb:
    annotations: # see: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.8/guide/ingress/annotations/
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
